# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cgrcompute.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cgrcompute.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63grcompute.proto\"K\n\x0bSemesterKey\x12\x14\n\x0cstudyProgram\x18\x01 \x01(\t\x12\x10\n\x08semester\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x61\x64\x65micYear\x18\x03 \x01(\t\"@\n\tCourseKey\x12\x10\n\x08\x63ourseNo\x18\x01 \x01(\t\x12!\n\x0bsemesterKey\x18\x02 \x01(\x0b\x32\x0c.SemesterKey\"u\n\x1b\x43ourseRecommendationRequest\x12\x0f\n\x07variant\x18\x01 \x01(\t\x12!\n\x0bsemesterKey\x18\x02 \x01(\x0b\x32\x0c.SemesterKey\x12\"\n\x0eselectedCourse\x18\x03 \x03(\x0b\x32\n.CourseKey\"\x99\x01\n\x1c\x43ourseRecommendationResponse\x12:\n\x06\x63ourse\x18\x02 \x03(\x0b\x32*.CourseRecommendationResponse.CourseDetail\x1a=\n\x0c\x43ourseDetail\x12\x17\n\x03key\x18\x01 \x01(\x0b\x32\n.CourseKey\x12\x14\n\x0c\x63ourseNameEn\x18\x02 \x01(\t2b\n\x14\x43ourseRecommendation\x12J\n\tRecommend\x12\x1c.CourseRecommendationRequest\x1a\x1d.CourseRecommendationResponse\"\x00\x62\x06proto3'
)




_SEMESTERKEY = _descriptor.Descriptor(
  name='SemesterKey',
  full_name='SemesterKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='studyProgram', full_name='SemesterKey.studyProgram', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='semester', full_name='SemesterKey.semester', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='academicYear', full_name='SemesterKey.academicYear', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=95,
)


_COURSEKEY = _descriptor.Descriptor(
  name='CourseKey',
  full_name='CourseKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='courseNo', full_name='CourseKey.courseNo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='semesterKey', full_name='CourseKey.semesterKey', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=161,
)


_COURSERECOMMENDATIONREQUEST = _descriptor.Descriptor(
  name='CourseRecommendationRequest',
  full_name='CourseRecommendationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='variant', full_name='CourseRecommendationRequest.variant', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='semesterKey', full_name='CourseRecommendationRequest.semesterKey', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selectedCourse', full_name='CourseRecommendationRequest.selectedCourse', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=280,
)


_COURSERECOMMENDATIONRESPONSE_COURSEDETAIL = _descriptor.Descriptor(
  name='CourseDetail',
  full_name='CourseRecommendationResponse.CourseDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CourseRecommendationResponse.CourseDetail.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='courseNameEn', full_name='CourseRecommendationResponse.CourseDetail.courseNameEn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=436,
)

_COURSERECOMMENDATIONRESPONSE = _descriptor.Descriptor(
  name='CourseRecommendationResponse',
  full_name='CourseRecommendationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='course', full_name='CourseRecommendationResponse.course', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_COURSERECOMMENDATIONRESPONSE_COURSEDETAIL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=436,
)

_COURSEKEY.fields_by_name['semesterKey'].message_type = _SEMESTERKEY
_COURSERECOMMENDATIONREQUEST.fields_by_name['semesterKey'].message_type = _SEMESTERKEY
_COURSERECOMMENDATIONREQUEST.fields_by_name['selectedCourse'].message_type = _COURSEKEY
_COURSERECOMMENDATIONRESPONSE_COURSEDETAIL.fields_by_name['key'].message_type = _COURSEKEY
_COURSERECOMMENDATIONRESPONSE_COURSEDETAIL.containing_type = _COURSERECOMMENDATIONRESPONSE
_COURSERECOMMENDATIONRESPONSE.fields_by_name['course'].message_type = _COURSERECOMMENDATIONRESPONSE_COURSEDETAIL
DESCRIPTOR.message_types_by_name['SemesterKey'] = _SEMESTERKEY
DESCRIPTOR.message_types_by_name['CourseKey'] = _COURSEKEY
DESCRIPTOR.message_types_by_name['CourseRecommendationRequest'] = _COURSERECOMMENDATIONREQUEST
DESCRIPTOR.message_types_by_name['CourseRecommendationResponse'] = _COURSERECOMMENDATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SemesterKey = _reflection.GeneratedProtocolMessageType('SemesterKey', (_message.Message,), {
  'DESCRIPTOR' : _SEMESTERKEY,
  '__module__' : 'cgrcompute_pb2'
  # @@protoc_insertion_point(class_scope:SemesterKey)
  })
_sym_db.RegisterMessage(SemesterKey)

CourseKey = _reflection.GeneratedProtocolMessageType('CourseKey', (_message.Message,), {
  'DESCRIPTOR' : _COURSEKEY,
  '__module__' : 'cgrcompute_pb2'
  # @@protoc_insertion_point(class_scope:CourseKey)
  })
_sym_db.RegisterMessage(CourseKey)

CourseRecommendationRequest = _reflection.GeneratedProtocolMessageType('CourseRecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _COURSERECOMMENDATIONREQUEST,
  '__module__' : 'cgrcompute_pb2'
  # @@protoc_insertion_point(class_scope:CourseRecommendationRequest)
  })
_sym_db.RegisterMessage(CourseRecommendationRequest)

CourseRecommendationResponse = _reflection.GeneratedProtocolMessageType('CourseRecommendationResponse', (_message.Message,), {

  'CourseDetail' : _reflection.GeneratedProtocolMessageType('CourseDetail', (_message.Message,), {
    'DESCRIPTOR' : _COURSERECOMMENDATIONRESPONSE_COURSEDETAIL,
    '__module__' : 'cgrcompute_pb2'
    # @@protoc_insertion_point(class_scope:CourseRecommendationResponse.CourseDetail)
    })
  ,
  'DESCRIPTOR' : _COURSERECOMMENDATIONRESPONSE,
  '__module__' : 'cgrcompute_pb2'
  # @@protoc_insertion_point(class_scope:CourseRecommendationResponse)
  })
_sym_db.RegisterMessage(CourseRecommendationResponse)
_sym_db.RegisterMessage(CourseRecommendationResponse.CourseDetail)



_COURSERECOMMENDATION = _descriptor.ServiceDescriptor(
  name='CourseRecommendation',
  full_name='CourseRecommendation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=438,
  serialized_end=536,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recommend',
    full_name='CourseRecommendation.Recommend',
    index=0,
    containing_service=None,
    input_type=_COURSERECOMMENDATIONREQUEST,
    output_type=_COURSERECOMMENDATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COURSERECOMMENDATION)

DESCRIPTOR.services_by_name['CourseRecommendation'] = _COURSERECOMMENDATION

# @@protoc_insertion_point(module_scope)
