# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cgrcompute.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63grcompute.proto\"K\n\x0bSemesterKey\x12\x14\n\x0cstudyProgram\x18\x01 \x01(\t\x12\x10\n\x08semester\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x61\x64\x65micYear\x18\x03 \x01(\t\"@\n\tCourseKey\x12\x10\n\x08\x63ourseNo\x18\x01 \x01(\t\x12!\n\x0bsemesterKey\x18\x02 \x01(\x0b\x32\x0c.SemesterKey\"v\n\x1b\x43ourseRecommendationRequest\x12\x0f\n\x07variant\x18\x01 \x01(\t\x12!\n\x0bsemesterKey\x18\x02 \x01(\x0b\x32\x0c.SemesterKey\x12#\n\x0fselectedCourses\x18\x03 \x03(\x0b\x32\n.CourseKey\"\x9a\x01\n\x1c\x43ourseRecommendationResponse\x12;\n\x07\x63ourses\x18\x02 \x03(\x0b\x32*.CourseRecommendationResponse.CourseDetail\x1a=\n\x0c\x43ourseDetail\x12\x17\n\x03key\x18\x01 \x01(\x0b\x32\n.CourseKey\x12\x14\n\x0c\x63ourseNameEn\x18\x02 \x01(\t2b\n\x14\x43ourseRecommendation\x12J\n\tRecommend\x12\x1c.CourseRecommendationRequest\x1a\x1d.CourseRecommendationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cgrcompute_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEMESTERKEY._serialized_start=20
  _SEMESTERKEY._serialized_end=95
  _COURSEKEY._serialized_start=97
  _COURSEKEY._serialized_end=161
  _COURSERECOMMENDATIONREQUEST._serialized_start=163
  _COURSERECOMMENDATIONREQUEST._serialized_end=281
  _COURSERECOMMENDATIONRESPONSE._serialized_start=284
  _COURSERECOMMENDATIONRESPONSE._serialized_end=438
  _COURSERECOMMENDATIONRESPONSE_COURSEDETAIL._serialized_start=377
  _COURSERECOMMENDATIONRESPONSE_COURSEDETAIL._serialized_end=438
  _COURSERECOMMENDATION._serialized_start=440
  _COURSERECOMMENDATION._serialized_end=538
# @@protoc_insertion_point(module_scope)
